### ISSUE TITLE
Package with red and black dominant layers are placed between the Presentation lane and oblivion

### ISSUE THREAD

**Issue by rsatrioadi** [christojeffrey/software-visualization-pack#4]
Input file that causes this: [SweetHome3D](https://github.com/rsatrioadi/phd/blob/main/data/bubbletea-viz/SweetHome3D-layers3-20240529-143330.csv)

![image](https://github.com/christojeffrey/software-visualization-pack/assets/181934/5df88134-1af4-45c7-bdfe-03c5a92c6dc2)

**Comment by rsatrioadi** [comment]
Another example: [JHotDraw](https://github.com/rsatrioadi/phd/blob/main/data/bubbletea-viz/jhotdraw-layers3-20240529-143223.csv)

![image](https://github.com/christojeffrey/software-visualization-pack/assets/181934/ab652df4-13ef-47da-b67b-00da8d701005)

**Comment by Adityapnn811** [comment]
By logic, it should be placed on the cross cutting section right?

**Comment by christojeffrey** [comment]
resolved. accidentally push the result directly to main branch hehe. changes [here](https://github.com/christojeffrey/software-visualization-pack/commit/fae07c47b2aa999e04c644b0c0d2efcb1a0bb46d)
